### ISSUE TITLE
Code Review 02/13/19

### ISSUE THREAD

**Issue by jonbirke0927** [Neminem1203/Me-Cube#1]
Hey Paul, project is looking good! A few comments below:

1. Reformat the sign in button to look more like that of the real site
2. Looks like YouTube redirects to a new url when clicking the signup button, perhaps consider doing the same
3. Once logged in, for the little account menu, make sure the labels are centered and are all the same size ("Your Channel" is larger than the rest)
4. After signing up, I am unable to logout; there are errors present in the console

Keep up the great progress!

**Comment by Neminem1203** [comment]
Finished Issue 1 and 3. 
#2: Is it okay if I keep it as a modal? I worked for a few days to make sure the signup and signin modals would not redirect the user (i prefer to make everything more dynamic)
#4: Can you send me a picture of the errors so I can debug it from my end? I tried logging out on my other browsers but i don't see an error.

**Comment by jonbirke0927** [comment]
#2: Fine by me, I'd maybe have it take up the entirety of the page at least, no need to change routes
#4: The error can be recreated by signing up a new user, then immediately trying to logout

**Comment by Neminem1203** [comment]
Error#4 fixed. I forgot to log_in!(@user) during the create function of the user.
#2: Do you think I should have a mostly transparent background with the same modal? (should I center it or keep it at the top right corner?)

**Comment by jonbirke0927** [comment]
#2: Since the real site redirects, I'd say a modal with a non transparent background would be a good addition. And yes, centered would be great. You can essentially achieve the same result with a modal as the real site does with the redirect

**Comment by Neminem1203** [comment]
fixed #2. When you have time, double check to make sure it's correct so I can close this issue.
