### ISSUE TITLE
Code / Style Review

### ISSUE THREAD

**Issue by jonbirke0927** [Neminem1203/Me-Cube#2]
Hey Paul, great progress on the app, it's looking awesome. A few comments below:
1. Consider resizing the upload and profile icons in the top righthand corner of the window, particularly the profile icon
2. When I click on the profile icon and see the dropdown, it might look a bit cleaner if it were shifted down a few more pixels so that it's not touching the profile icon itself
3. When I click on "Your Channel" in the profile dropdown menu, the app errors out
4. Consider tweaking the positioning of the elements on the "Your Account" page from the dropdown; as it currently stands, it seems a bit unorganized
5. The profile dropdown should close automatically if I click somewhere else on the page; the user should have to manually close it
6. I'd consider tweaking the formatting / positioning of elements on the upload page, it looks a bit bare as it currently stands

Overall, this is coming along really great. Keep it up Paul!

**Comment by Neminem1203** [comment]
#1 made profile icon smaller (which in turn kinda fixed #2). Tell me if you think I need to move it down more or downsize the icon.
#3 was an issue that I was working on. It should be working now.
#4 Honestly, I'm not sure what else to do with it. Do you have any directions as to what I should do with the items?
#5 i made it so if you click outside the dropdown it will close it, but i set it at opacity 50% to show you that you can't interact with anything on the page until the dropdown is gone. do you have an alternative to this?
#6 created some icons and made it look nice with some hover effects and active effects. Any other advice on what I should put here?
